// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: dashboard.proto

package dashboard

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OverviewCardInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         int32                  `protobuf:"varint,1,opt,name=users,proto3" json:"users,omitempty"`
	Merchants     int32                  `protobuf:"varint,2,opt,name=merchants,proto3" json:"merchants,omitempty"`
	ApiRequests   int32                  `protobuf:"varint,3,opt,name=api_requests,json=apiRequests,proto3" json:"api_requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverviewCardInfoResponse) Reset() {
	*x = OverviewCardInfoResponse{}
	mi := &file_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverviewCardInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverviewCardInfoResponse) ProtoMessage() {}

func (x *OverviewCardInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverviewCardInfoResponse.ProtoReflect.Descriptor instead.
func (*OverviewCardInfoResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{0}
}

func (x *OverviewCardInfoResponse) GetUsers() int32 {
	if x != nil {
		return x.Users
	}
	return 0
}

func (x *OverviewCardInfoResponse) GetMerchants() int32 {
	if x != nil {
		return x.Merchants
	}
	return 0
}

func (x *OverviewCardInfoResponse) GetApiRequests() int32 {
	if x != nil {
		return x.ApiRequests
	}
	return 0
}

type UserStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         int32                  `protobuf:"varint,1,opt,name=users,proto3" json:"users,omitempty"`
	ActiveUsers   int32                  `protobuf:"varint,2,opt,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`
	InactiveUsers int32                  `protobuf:"varint,3,opt,name=inactive_users,json=inactiveUsers,proto3" json:"inactive_users,omitempty"`
	AdminUsers    int32                  `protobuf:"varint,4,opt,name=adminUsers,proto3" json:"adminUsers,omitempty"`
	MerchantUsers int32                  `protobuf:"varint,5,opt,name=merchantUsers,proto3" json:"merchantUsers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStatisticsResponse) Reset() {
	*x = UserStatisticsResponse{}
	mi := &file_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStatisticsResponse) ProtoMessage() {}

func (x *UserStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStatisticsResponse.ProtoReflect.Descriptor instead.
func (*UserStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{1}
}

func (x *UserStatisticsResponse) GetUsers() int32 {
	if x != nil {
		return x.Users
	}
	return 0
}

func (x *UserStatisticsResponse) GetActiveUsers() int32 {
	if x != nil {
		return x.ActiveUsers
	}
	return 0
}

func (x *UserStatisticsResponse) GetInactiveUsers() int32 {
	if x != nil {
		return x.InactiveUsers
	}
	return 0
}

func (x *UserStatisticsResponse) GetAdminUsers() int32 {
	if x != nil {
		return x.AdminUsers
	}
	return 0
}

func (x *UserStatisticsResponse) GetMerchantUsers() int32 {
	if x != nil {
		return x.MerchantUsers
	}
	return 0
}

type UserRoleStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminUsers    int32                  `protobuf:"varint,1,opt,name=admin_users,json=adminUsers,proto3" json:"admin_users,omitempty"`
	MerchantUsers int32                  `protobuf:"varint,2,opt,name=merchant_users,json=merchantUsers,proto3" json:"merchant_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRoleStatisticsResponse) Reset() {
	*x = UserRoleStatisticsResponse{}
	mi := &file_dashboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRoleStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRoleStatisticsResponse) ProtoMessage() {}

func (x *UserRoleStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRoleStatisticsResponse.ProtoReflect.Descriptor instead.
func (*UserRoleStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{2}
}

func (x *UserRoleStatisticsResponse) GetAdminUsers() int32 {
	if x != nil {
		return x.AdminUsers
	}
	return 0
}

func (x *UserRoleStatisticsResponse) GetMerchantUsers() int32 {
	if x != nil {
		return x.MerchantUsers
	}
	return 0
}

type MerchantStatisticsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Merchants         int32                  `protobuf:"varint,1,opt,name=merchants,proto3" json:"merchants,omitempty"`
	ActiveMerchants   int32                  `protobuf:"varint,2,opt,name=active_merchants,json=activeMerchants,proto3" json:"active_merchants,omitempty"`
	InactiveMerchants int32                  `protobuf:"varint,3,opt,name=inactive_merchants,json=inactiveMerchants,proto3" json:"inactive_merchants,omitempty"`
	NewToday          int32                  `protobuf:"varint,4,opt,name=newToday,proto3" json:"newToday,omitempty"`
	NewMonth          int32                  `protobuf:"varint,5,opt,name=newMonth,proto3" json:"newMonth,omitempty"`
	NewWeek           int32                  `protobuf:"varint,6,opt,name=newWeek,proto3" json:"newWeek,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MerchantStatisticsResponse) Reset() {
	*x = MerchantStatisticsResponse{}
	mi := &file_dashboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantStatisticsResponse) ProtoMessage() {}

func (x *MerchantStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantStatisticsResponse.ProtoReflect.Descriptor instead.
func (*MerchantStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{3}
}

func (x *MerchantStatisticsResponse) GetMerchants() int32 {
	if x != nil {
		return x.Merchants
	}
	return 0
}

func (x *MerchantStatisticsResponse) GetActiveMerchants() int32 {
	if x != nil {
		return x.ActiveMerchants
	}
	return 0
}

func (x *MerchantStatisticsResponse) GetInactiveMerchants() int32 {
	if x != nil {
		return x.InactiveMerchants
	}
	return 0
}

func (x *MerchantStatisticsResponse) GetNewToday() int32 {
	if x != nil {
		return x.NewToday
	}
	return 0
}

func (x *MerchantStatisticsResponse) GetNewMonth() int32 {
	if x != nil {
		return x.NewMonth
	}
	return 0
}

func (x *MerchantStatisticsResponse) GetNewWeek() int32 {
	if x != nil {
		return x.NewWeek
	}
	return 0
}

type TopMerchantsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MerchantOne        string                 `protobuf:"bytes,1,opt,name=merchant_one,json=merchantOne,proto3" json:"merchant_one,omitempty"`
	MerchantTwo        string                 `protobuf:"bytes,2,opt,name=merchant_two,json=merchantTwo,proto3" json:"merchant_two,omitempty"`
	MerchantThree      string                 `protobuf:"bytes,3,opt,name=merchant_three,json=merchantThree,proto3" json:"merchant_three,omitempty"`
	MerchantOneCount   int32                  `protobuf:"varint,4,opt,name=merchant_one_count,json=merchantOneCount,proto3" json:"merchant_one_count,omitempty"`
	MerchantTwoCount   int32                  `protobuf:"varint,5,opt,name=merchant_two_count,json=merchantTwoCount,proto3" json:"merchant_two_count,omitempty"`
	MerchantThreeCount int32                  `protobuf:"varint,6,opt,name=merchant_three_count,json=merchantThreeCount,proto3" json:"merchant_three_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TopMerchantsResponse) Reset() {
	*x = TopMerchantsResponse{}
	mi := &file_dashboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopMerchantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopMerchantsResponse) ProtoMessage() {}

func (x *TopMerchantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopMerchantsResponse.ProtoReflect.Descriptor instead.
func (*TopMerchantsResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{4}
}

func (x *TopMerchantsResponse) GetMerchantOne() string {
	if x != nil {
		return x.MerchantOne
	}
	return ""
}

func (x *TopMerchantsResponse) GetMerchantTwo() string {
	if x != nil {
		return x.MerchantTwo
	}
	return ""
}

func (x *TopMerchantsResponse) GetMerchantThree() string {
	if x != nil {
		return x.MerchantThree
	}
	return ""
}

func (x *TopMerchantsResponse) GetMerchantOneCount() int32 {
	if x != nil {
		return x.MerchantOneCount
	}
	return 0
}

func (x *TopMerchantsResponse) GetMerchantTwoCount() int32 {
	if x != nil {
		return x.MerchantTwoCount
	}
	return 0
}

func (x *TopMerchantsResponse) GetMerchantThreeCount() int32 {
	if x != nil {
		return x.MerchantThreeCount
	}
	return 0
}

type APIStatisticsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Requests       int32                  `protobuf:"varint,1,opt,name=requests,proto3" json:"requests,omitempty"`
	RequestsToday  int32                  `protobuf:"varint,2,opt,name=requests_today,json=requestsToday,proto3" json:"requests_today,omitempty"`
	ErrorRate      int32                  `protobuf:"varint,3,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	Endpoint1      string                 `protobuf:"bytes,4,opt,name=endpoint1,proto3" json:"endpoint1,omitempty"`
	Endpoint2      string                 `protobuf:"bytes,5,opt,name=endpoint2,proto3" json:"endpoint2,omitempty"`
	Endpoint3      string                 `protobuf:"bytes,6,opt,name=endpoint3,proto3" json:"endpoint3,omitempty"`
	Endpoint1Count string                 `protobuf:"bytes,7,opt,name=endpoint1Count,proto3" json:"endpoint1Count,omitempty"`
	Endpoint2Count string                 `protobuf:"bytes,8,opt,name=endpoint2Count,proto3" json:"endpoint2Count,omitempty"`
	Endpoint3Count string                 `protobuf:"bytes,9,opt,name=endpoint3Count,proto3" json:"endpoint3Count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *APIStatisticsResponse) Reset() {
	*x = APIStatisticsResponse{}
	mi := &file_dashboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIStatisticsResponse) ProtoMessage() {}

func (x *APIStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIStatisticsResponse.ProtoReflect.Descriptor instead.
func (*APIStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{5}
}

func (x *APIStatisticsResponse) GetRequests() int32 {
	if x != nil {
		return x.Requests
	}
	return 0
}

func (x *APIStatisticsResponse) GetRequestsToday() int32 {
	if x != nil {
		return x.RequestsToday
	}
	return 0
}

func (x *APIStatisticsResponse) GetErrorRate() int32 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *APIStatisticsResponse) GetEndpoint1() string {
	if x != nil {
		return x.Endpoint1
	}
	return ""
}

func (x *APIStatisticsResponse) GetEndpoint2() string {
	if x != nil {
		return x.Endpoint2
	}
	return ""
}

func (x *APIStatisticsResponse) GetEndpoint3() string {
	if x != nil {
		return x.Endpoint3
	}
	return ""
}

func (x *APIStatisticsResponse) GetEndpoint1Count() string {
	if x != nil {
		return x.Endpoint1Count
	}
	return ""
}

func (x *APIStatisticsResponse) GetEndpoint2Count() string {
	if x != nil {
		return x.Endpoint2Count
	}
	return ""
}

func (x *APIStatisticsResponse) GetEndpoint3Count() string {
	if x != nil {
		return x.Endpoint3Count
	}
	return ""
}

type APIResTimeStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint1     string                 `protobuf:"bytes,1,opt,name=endpoint1,proto3" json:"endpoint1,omitempty"`
	Endpoint2     string                 `protobuf:"bytes,2,opt,name=endpoint2,proto3" json:"endpoint2,omitempty"`
	Endpoint3     string                 `protobuf:"bytes,3,opt,name=endpoint3,proto3" json:"endpoint3,omitempty"`
	Endpoint1Time string                 `protobuf:"bytes,7,opt,name=endpoint1Time,proto3" json:"endpoint1Time,omitempty"`
	Endpoint2Time string                 `protobuf:"bytes,8,opt,name=endpoint2Time,proto3" json:"endpoint2Time,omitempty"`
	Endpoint3Time string                 `protobuf:"bytes,9,opt,name=endpoint3Time,proto3" json:"endpoint3Time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIResTimeStatisticsResponse) Reset() {
	*x = APIResTimeStatisticsResponse{}
	mi := &file_dashboard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIResTimeStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIResTimeStatisticsResponse) ProtoMessage() {}

func (x *APIResTimeStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIResTimeStatisticsResponse.ProtoReflect.Descriptor instead.
func (*APIResTimeStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{6}
}

func (x *APIResTimeStatisticsResponse) GetEndpoint1() string {
	if x != nil {
		return x.Endpoint1
	}
	return ""
}

func (x *APIResTimeStatisticsResponse) GetEndpoint2() string {
	if x != nil {
		return x.Endpoint2
	}
	return ""
}

func (x *APIResTimeStatisticsResponse) GetEndpoint3() string {
	if x != nil {
		return x.Endpoint3
	}
	return ""
}

func (x *APIResTimeStatisticsResponse) GetEndpoint1Time() string {
	if x != nil {
		return x.Endpoint1Time
	}
	return ""
}

func (x *APIResTimeStatisticsResponse) GetEndpoint2Time() string {
	if x != nil {
		return x.Endpoint2Time
	}
	return ""
}

func (x *APIResTimeStatisticsResponse) GetEndpoint3Time() string {
	if x != nil {
		return x.Endpoint3Time
	}
	return ""
}

type TransactionStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  int32                  `protobuf:"varint,1,opt,name=transactions,proto3" json:"transactions,omitempty"`
	Successful    int32                  `protobuf:"varint,2,opt,name=successful,proto3" json:"successful,omitempty"`
	Failed        int32                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	Pending       int32                  `protobuf:"varint,4,opt,name=pending,proto3" json:"pending,omitempty"`
	TotalAmount   int32                  `protobuf:"varint,5,opt,name=totalAmount,proto3" json:"totalAmount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionStatisticsResponse) Reset() {
	*x = TransactionStatisticsResponse{}
	mi := &file_dashboard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionStatisticsResponse) ProtoMessage() {}

func (x *TransactionStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionStatisticsResponse.ProtoReflect.Descriptor instead.
func (*TransactionStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{7}
}

func (x *TransactionStatisticsResponse) GetTransactions() int32 {
	if x != nil {
		return x.Transactions
	}
	return 0
}

func (x *TransactionStatisticsResponse) GetSuccessful() int32 {
	if x != nil {
		return x.Successful
	}
	return 0
}

func (x *TransactionStatisticsResponse) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *TransactionStatisticsResponse) GetPending() int32 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *TransactionStatisticsResponse) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type TransactionChannelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mtn           int32                  `protobuf:"varint,1,opt,name=mtn,proto3" json:"mtn,omitempty"`
	Zamtel        int32                  `protobuf:"varint,2,opt,name=zamtel,proto3" json:"zamtel,omitempty"`
	Airtel        int32                  `protobuf:"varint,3,opt,name=airtel,proto3" json:"airtel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionChannelsResponse) Reset() {
	*x = TransactionChannelsResponse{}
	mi := &file_dashboard_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionChannelsResponse) ProtoMessage() {}

func (x *TransactionChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionChannelsResponse.ProtoReflect.Descriptor instead.
func (*TransactionChannelsResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{8}
}

func (x *TransactionChannelsResponse) GetMtn() int32 {
	if x != nil {
		return x.Mtn
	}
	return 0
}

func (x *TransactionChannelsResponse) GetZamtel() int32 {
	if x != nil {
		return x.Zamtel
	}
	return 0
}

func (x *TransactionChannelsResponse) GetAirtel() int32 {
	if x != nil {
		return x.Airtel
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fullname      string                 `protobuf:"bytes,1,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_dashboard_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{9}
}

func (x *User) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reference     string                 `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Customer      string                 `protobuf:"bytes,3,opt,name=customer,proto3" json:"customer,omitempty"`
	Channel       string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Narration     string                 `protobuf:"bytes,8,opt,name=narration,proto3" json:"narration,omitempty"`
	Date          string                 `protobuf:"bytes,9,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_dashboard_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{10}
}

func (x *Transaction) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *Transaction) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Transaction) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

func (x *Transaction) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Transaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Transaction) GetNarration() string {
	if x != nil {
		return x.Narration
	}
	return ""
}

func (x *Transaction) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type API struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Ipaddress     string                 `protobuf:"bytes,5,opt,name=ipaddress,proto3" json:"ipaddress,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	ResponseTime  string                 `protobuf:"bytes,7,opt,name=response_time,json=responseTime,proto3" json:"response_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *API) Reset() {
	*x = API{}
	mi := &file_dashboard_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *API) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*API) ProtoMessage() {}

func (x *API) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use API.ProtoReflect.Descriptor instead.
func (*API) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{11}
}

func (x *API) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *API) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *API) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *API) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *API) GetIpaddress() string {
	if x != nil {
		return x.Ipaddress
	}
	return ""
}

func (x *API) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *API) GetResponseTime() string {
	if x != nil {
		return x.ResponseTime
	}
	return ""
}

type Activity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Entity        string                 `protobuf:"bytes,3,opt,name=entity,proto3" json:"entity,omitempty"`
	EntityId      string                 `protobuf:"bytes,4,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Ipaddress     string                 `protobuf:"bytes,5,opt,name=ipaddress,proto3" json:"ipaddress,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Activity) Reset() {
	*x = Activity{}
	mi := &file_dashboard_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Activity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activity) ProtoMessage() {}

func (x *Activity) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activity.ProtoReflect.Descriptor instead.
func (*Activity) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{12}
}

func (x *Activity) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Activity) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Activity) GetEntity() string {
	if x != nil {
		return x.Entity
	}
	return ""
}

func (x *Activity) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Activity) GetIpaddress() string {
	if x != nil {
		return x.Ipaddress
	}
	return ""
}

func (x *Activity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTransactionsRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Page                 int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	UserId               string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TransactionType      string                 `protobuf:"bytes,4,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"`
	StartDate            string                 `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate              string                 `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Status               string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Channel              string                 `protobuf:"bytes,8,opt,name=channel,proto3" json:"channel,omitempty"`
	ExternalReference    string                 `protobuf:"bytes,9,opt,name=external_reference,json=externalReference,proto3" json:"external_reference,omitempty"`
	TransactionReference string                 `protobuf:"bytes,10,opt,name=transaction_reference,json=transactionReference,proto3" json:"transaction_reference,omitempty"`
	Customer             string                 `protobuf:"bytes,11,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetTransactionsRequest) Reset() {
	*x = GetTransactionsRequest{}
	mi := &file_dashboard_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsRequest) ProtoMessage() {}

func (x *GetTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{13}
}

func (x *GetTransactionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetTransactionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetTransactionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetTransactionsRequest) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *GetTransactionsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetTransactionsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *GetTransactionsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetTransactionsRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *GetTransactionsRequest) GetExternalReference() string {
	if x != nil {
		return x.ExternalReference
	}
	return ""
}

func (x *GetTransactionsRequest) GetTransactionReference() string {
	if x != nil {
		return x.TransactionReference
	}
	return ""
}

func (x *GetTransactionsRequest) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

type GetTransactionsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Transactions      []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`                                     // List of users
	TotalPages        int32                  `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`                      // Total number of pages
	CurrentPage       int32                  `protobuf:"varint,3,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`                   // Current page
	HasMore           bool                   `protobuf:"varint,4,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`                               // Whether there are more pages
	TotalTransactions int32                  `protobuf:"varint,5,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"` // Total number of transactions
	TotalSuccessful   int32                  `protobuf:"varint,6,opt,name=total_successful,json=totalSuccessful,proto3" json:"total_successful,omitempty"`       // Total number of successful transactions
	TotalFailed       int32                  `protobuf:"varint,7,opt,name=total_failed,json=totalFailed,proto3" json:"total_failed,omitempty"`                   // Total number of failed transactions
	TotalPending      int32                  `protobuf:"varint,8,opt,name=total_pending,json=totalPending,proto3" json:"total_pending,omitempty"`                // Total number of pending transactions
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetTransactionsResponse) Reset() {
	*x = GetTransactionsResponse{}
	mi := &file_dashboard_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsResponse) ProtoMessage() {}

func (x *GetTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{14}
}

func (x *GetTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *GetTransactionsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetTransactionsResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetTransactionsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetTransactionsResponse) GetTotalTransactions() int32 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *GetTransactionsResponse) GetTotalSuccessful() int32 {
	if x != nil {
		return x.TotalSuccessful
	}
	return 0
}

func (x *GetTransactionsResponse) GetTotalFailed() int32 {
	if x != nil {
		return x.TotalFailed
	}
	return 0
}

func (x *GetTransactionsResponse) GetTotalPending() int32 {
	if x != nil {
		return x.TotalPending
	}
	return 0
}

type GetUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersRequest) Reset() {
	*x = GetUsersRequest{}
	mi := &file_dashboard_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersRequest) ProtoMessage() {}

func (x *GetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersRequest.ProtoReflect.Descriptor instead.
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{15}
}

func (x *GetUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          []*User                `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`                // List of users
	TotalPages    int32                  `protobuf:"varint,2,opt,name=totalPages,proto3" json:"totalPages,omitempty"`   // Total number of pages
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=currentPage,proto3" json:"currentPage,omitempty"` // Current page
	HasMore       bool                   `protobuf:"varint,4,opt,name=hasMore,proto3" json:"hasMore,omitempty"`         // Whether there are more pages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersResponse) Reset() {
	*x = GetUsersResponse{}
	mi := &file_dashboard_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersResponse) ProtoMessage() {}

func (x *GetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersResponse.ProtoReflect.Descriptor instead.
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{16}
}

func (x *GetUsersResponse) GetUser() []*User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetUsersResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetUsersResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetUsersResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetAPIrequests struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAPIrequests) Reset() {
	*x = GetAPIrequests{}
	mi := &file_dashboard_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAPIrequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAPIrequests) ProtoMessage() {}

func (x *GetAPIrequests) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAPIrequests.ProtoReflect.Descriptor instead.
func (*GetAPIrequests) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{17}
}

func (x *GetAPIrequests) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAPIrequests) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetAPIReqsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       []*API                 `protobuf:"bytes,1,rep,name=request,proto3" json:"request,omitempty"`          // List of users
	TotalPages    int32                  `protobuf:"varint,2,opt,name=totalPages,proto3" json:"totalPages,omitempty"`   // Total number of pages
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=currentPage,proto3" json:"currentPage,omitempty"` // Current page
	HasMore       bool                   `protobuf:"varint,4,opt,name=hasMore,proto3" json:"hasMore,omitempty"`         // Whether there are more pages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAPIReqsResponse) Reset() {
	*x = GetAPIReqsResponse{}
	mi := &file_dashboard_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAPIReqsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAPIReqsResponse) ProtoMessage() {}

func (x *GetAPIReqsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAPIReqsResponse.ProtoReflect.Descriptor instead.
func (*GetAPIReqsResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{18}
}

func (x *GetAPIReqsResponse) GetRequest() []*API {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *GetAPIReqsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetAPIReqsResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetAPIReqsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetActivityrequests struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityrequests) Reset() {
	*x = GetActivityrequests{}
	mi := &file_dashboard_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityrequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityrequests) ProtoMessage() {}

func (x *GetActivityrequests) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityrequests.ProtoReflect.Descriptor instead.
func (*GetActivityrequests) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{19}
}

func (x *GetActivityrequests) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetActivityrequests) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activity      []*Activity            `protobuf:"bytes,1,rep,name=activity,proto3" json:"activity,omitempty"`        // List of users
	TotalPages    int32                  `protobuf:"varint,2,opt,name=totalPages,proto3" json:"totalPages,omitempty"`   // Total number of pages
	CurrentPage   int32                  `protobuf:"varint,3,opt,name=currentPage,proto3" json:"currentPage,omitempty"` // Current page
	HasMore       bool                   `protobuf:"varint,4,opt,name=hasMore,proto3" json:"hasMore,omitempty"`         // Whether there are more pages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityResponse) Reset() {
	*x = GetActivityResponse{}
	mi := &file_dashboard_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityResponse) ProtoMessage() {}

func (x *GetActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityResponse.ProtoReflect.Descriptor instead.
func (*GetActivityResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{20}
}

func (x *GetActivityResponse) GetActivity() []*Activity {
	if x != nil {
		return x.Activity
	}
	return nil
}

func (x *GetActivityResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *GetActivityResponse) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *GetActivityResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type EditUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fullname      string                 `protobuf:"bytes,1,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditUserRequest) Reset() {
	*x = EditUserRequest{}
	mi := &file_dashboard_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditUserRequest) ProtoMessage() {}

func (x *EditUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditUserRequest.ProtoReflect.Descriptor instead.
func (*EditUserRequest) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{21}
}

func (x *EditUserRequest) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *EditUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EditUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *EditUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *EditUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *EditUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EditUserRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Portal        string                 `protobuf:"bytes,3,opt,name=portal,proto3" json:"portal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_dashboard_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{22}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetPortal() string {
	if x != nil {
		return x.Portal
	}
	return ""
}

type DashboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	Permissions   []string               `protobuf:"bytes,7,rep,name=permissions,proto3" json:"permissions,omitempty"` // List of permissions granted to the user
	TokenExpiry   string                 `protobuf:"bytes,9,opt,name=tokenExpiry,proto3" json:"tokenExpiry,omitempty"`
	EmailVerified bool                   `protobuf:"varint,10,opt,name=emailVerified,proto3" json:"emailVerified,omitempty"`
	AccountStatus string                 `protobuf:"bytes,11,opt,name=accountStatus,proto3" json:"accountStatus,omitempty"`
	Email         string                 `protobuf:"bytes,12,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardResponse) Reset() {
	*x = DashboardResponse{}
	mi := &file_dashboard_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardResponse) ProtoMessage() {}

func (x *DashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dashboard_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardResponse.ProtoReflect.Descriptor instead.
func (*DashboardResponse) Descriptor() ([]byte, []int) {
	return file_dashboard_proto_rawDescGZIP(), []int{23}
}

func (x *DashboardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DashboardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DashboardResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DashboardResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DashboardResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *DashboardResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DashboardResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *DashboardResponse) GetTokenExpiry() string {
	if x != nil {
		return x.TokenExpiry
	}
	return ""
}

func (x *DashboardResponse) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *DashboardResponse) GetAccountStatus() string {
	if x != nil {
		return x.AccountStatus
	}
	return ""
}

func (x *DashboardResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_dashboard_proto protoreflect.FileDescriptor

const file_dashboard_proto_rawDesc = "" +
	"\n" +
	"\x0fdashboard.proto\x12\tdashboard\"q\n" +
	"\x18OverviewCardInfoResponse\x12\x14\n" +
	"\x05users\x18\x01 \x01(\x05R\x05users\x12\x1c\n" +
	"\tmerchants\x18\x02 \x01(\x05R\tmerchants\x12!\n" +
	"\fapi_requests\x18\x03 \x01(\x05R\vapiRequests\"\xbe\x01\n" +
	"\x16UserStatisticsResponse\x12\x14\n" +
	"\x05users\x18\x01 \x01(\x05R\x05users\x12!\n" +
	"\factive_users\x18\x02 \x01(\x05R\vactiveUsers\x12%\n" +
	"\x0einactive_users\x18\x03 \x01(\x05R\rinactiveUsers\x12\x1e\n" +
	"\n" +
	"adminUsers\x18\x04 \x01(\x05R\n" +
	"adminUsers\x12$\n" +
	"\rmerchantUsers\x18\x05 \x01(\x05R\rmerchantUsers\"d\n" +
	"\x1aUserRoleStatisticsResponse\x12\x1f\n" +
	"\vadmin_users\x18\x01 \x01(\x05R\n" +
	"adminUsers\x12%\n" +
	"\x0emerchant_users\x18\x02 \x01(\x05R\rmerchantUsers\"\xe6\x01\n" +
	"\x1aMerchantStatisticsResponse\x12\x1c\n" +
	"\tmerchants\x18\x01 \x01(\x05R\tmerchants\x12)\n" +
	"\x10active_merchants\x18\x02 \x01(\x05R\x0factiveMerchants\x12-\n" +
	"\x12inactive_merchants\x18\x03 \x01(\x05R\x11inactiveMerchants\x12\x1a\n" +
	"\bnewToday\x18\x04 \x01(\x05R\bnewToday\x12\x1a\n" +
	"\bnewMonth\x18\x05 \x01(\x05R\bnewMonth\x12\x18\n" +
	"\anewWeek\x18\x06 \x01(\x05R\anewWeek\"\x91\x02\n" +
	"\x14TopMerchantsResponse\x12!\n" +
	"\fmerchant_one\x18\x01 \x01(\tR\vmerchantOne\x12!\n" +
	"\fmerchant_two\x18\x02 \x01(\tR\vmerchantTwo\x12%\n" +
	"\x0emerchant_three\x18\x03 \x01(\tR\rmerchantThree\x12,\n" +
	"\x12merchant_one_count\x18\x04 \x01(\x05R\x10merchantOneCount\x12,\n" +
	"\x12merchant_two_count\x18\x05 \x01(\x05R\x10merchantTwoCount\x120\n" +
	"\x14merchant_three_count\x18\x06 \x01(\x05R\x12merchantThreeCount\"\xcb\x02\n" +
	"\x15APIStatisticsResponse\x12\x1a\n" +
	"\brequests\x18\x01 \x01(\x05R\brequests\x12%\n" +
	"\x0erequests_today\x18\x02 \x01(\x05R\rrequestsToday\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x03 \x01(\x05R\terrorRate\x12\x1c\n" +
	"\tendpoint1\x18\x04 \x01(\tR\tendpoint1\x12\x1c\n" +
	"\tendpoint2\x18\x05 \x01(\tR\tendpoint2\x12\x1c\n" +
	"\tendpoint3\x18\x06 \x01(\tR\tendpoint3\x12&\n" +
	"\x0eendpoint1Count\x18\a \x01(\tR\x0eendpoint1Count\x12&\n" +
	"\x0eendpoint2Count\x18\b \x01(\tR\x0eendpoint2Count\x12&\n" +
	"\x0eendpoint3Count\x18\t \x01(\tR\x0eendpoint3Count\"\xea\x01\n" +
	"\x1cAPIResTimeStatisticsResponse\x12\x1c\n" +
	"\tendpoint1\x18\x01 \x01(\tR\tendpoint1\x12\x1c\n" +
	"\tendpoint2\x18\x02 \x01(\tR\tendpoint2\x12\x1c\n" +
	"\tendpoint3\x18\x03 \x01(\tR\tendpoint3\x12$\n" +
	"\rendpoint1Time\x18\a \x01(\tR\rendpoint1Time\x12$\n" +
	"\rendpoint2Time\x18\b \x01(\tR\rendpoint2Time\x12$\n" +
	"\rendpoint3Time\x18\t \x01(\tR\rendpoint3Time\"\xb7\x01\n" +
	"\x1dTransactionStatisticsResponse\x12\"\n" +
	"\ftransactions\x18\x01 \x01(\x05R\ftransactions\x12\x1e\n" +
	"\n" +
	"successful\x18\x02 \x01(\x05R\n" +
	"successful\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x05R\x06failed\x12\x18\n" +
	"\apending\x18\x04 \x01(\x05R\apending\x12 \n" +
	"\vtotalAmount\x18\x05 \x01(\x05R\vtotalAmount\"_\n" +
	"\x1bTransactionChannelsResponse\x12\x10\n" +
	"\x03mtn\x18\x01 \x01(\x05R\x03mtn\x12\x16\n" +
	"\x06zamtel\x18\x02 \x01(\x05R\x06zamtel\x12\x16\n" +
	"\x06airtel\x18\x03 \x01(\x05R\x06airtel\"\xa6\x01\n" +
	"\x04User\x12\x1a\n" +
	"\bfullname\x18\x01 \x01(\tR\bfullname\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"\xe7\x01\n" +
	"\vTransaction\x12\x1c\n" +
	"\treference\x18\x01 \x01(\tR\treference\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcustomer\x18\x03 \x01(\tR\bcustomer\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1c\n" +
	"\tnarration\x18\b \x01(\tR\tnarration\x12\x12\n" +
	"\x04date\x18\t \x01(\tR\x04date\"\xbd\x01\n" +
	"\x03API\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x1c\n" +
	"\tipaddress\x18\x05 \x01(\tR\tipaddress\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\tR\x02id\x12#\n" +
	"\rresponse_time\x18\a \x01(\tR\fresponseTime\"\x9e\x01\n" +
	"\bActivity\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x16\n" +
	"\x06entity\x18\x03 \x01(\tR\x06entity\x12\x1b\n" +
	"\tentity_id\x18\x04 \x01(\tR\bentityId\x12\x1c\n" +
	"\tipaddress\x18\x05 \x01(\tR\tipaddress\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\tR\x02id\"\xf8\x02\n" +
	"\x16GetTransactionsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12)\n" +
	"\x10transaction_type\x18\x04 \x01(\tR\x0ftransactionType\x12\x1d\n" +
	"\n" +
	"start_date\x18\x05 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x06 \x01(\tR\aendDate\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x18\n" +
	"\achannel\x18\b \x01(\tR\achannel\x12-\n" +
	"\x12external_reference\x18\t \x01(\tR\x11externalReference\x123\n" +
	"\x15transaction_reference\x18\n" +
	" \x01(\tR\x14transactionReference\x12\x1a\n" +
	"\bcustomer\x18\v \x01(\tR\bcustomer\"\xd6\x02\n" +
	"\x17GetTransactionsResponse\x12:\n" +
	"\ftransactions\x18\x01 \x03(\v2\x16.dashboard.TransactionR\ftransactions\x12\x1f\n" +
	"\vtotal_pages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12!\n" +
	"\fcurrent_page\x18\x03 \x01(\x05R\vcurrentPage\x12\x19\n" +
	"\bhas_more\x18\x04 \x01(\bR\ahasMore\x12-\n" +
	"\x12total_transactions\x18\x05 \x01(\x05R\x11totalTransactions\x12)\n" +
	"\x10total_successful\x18\x06 \x01(\x05R\x0ftotalSuccessful\x12!\n" +
	"\ftotal_failed\x18\a \x01(\x05R\vtotalFailed\x12#\n" +
	"\rtotal_pending\x18\b \x01(\x05R\ftotalPending\"A\n" +
	"\x0fGetUsersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\"\x93\x01\n" +
	"\x10GetUsersResponse\x12#\n" +
	"\x04user\x18\x01 \x03(\v2\x0f.dashboard.UserR\x04user\x12\x1e\n" +
	"\n" +
	"totalPages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12 \n" +
	"\vcurrentPage\x18\x03 \x01(\x05R\vcurrentPage\x12\x18\n" +
	"\ahasMore\x18\x04 \x01(\bR\ahasMore\"@\n" +
	"\x0eGetAPIrequests\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\"\x9a\x01\n" +
	"\x12GetAPIReqsResponse\x12(\n" +
	"\arequest\x18\x01 \x03(\v2\x0e.dashboard.APIR\arequest\x12\x1e\n" +
	"\n" +
	"totalPages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12 \n" +
	"\vcurrentPage\x18\x03 \x01(\x05R\vcurrentPage\x12\x18\n" +
	"\ahasMore\x18\x04 \x01(\bR\ahasMore\"E\n" +
	"\x13GetActivityrequests\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\"\xa2\x01\n" +
	"\x13GetActivityResponse\x12/\n" +
	"\bactivity\x18\x01 \x03(\v2\x13.dashboard.ActivityR\bactivity\x12\x1e\n" +
	"\n" +
	"totalPages\x18\x02 \x01(\x05R\n" +
	"totalPages\x12 \n" +
	"\vcurrentPage\x18\x03 \x01(\x05R\vcurrentPage\x12\x18\n" +
	"\ahasMore\x18\x04 \x01(\bR\ahasMore\"\xb1\x01\n" +
	"\x0fEditUserRequest\x12\x1a\n" +
	"\bfullname\x18\x01 \x01(\tR\bfullname\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"X\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x16\n" +
	"\x06portal\x18\x03 \x01(\tR\x06portal\"\xbf\x02\n" +
	"\x11dashboardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\tR\x02id\x12 \n" +
	"\vpermissions\x18\a \x03(\tR\vpermissions\x12 \n" +
	"\vtokenExpiry\x18\t \x01(\tR\vtokenExpiry\x12$\n" +
	"\remailVerified\x18\n" +
	" \x01(\bR\remailVerified\x12$\n" +
	"\raccountStatus\x18\v \x01(\tR\raccountStatus\x12\x14\n" +
	"\x05email\x18\f \x01(\tR\x05emailB\x1cZ\x1a/proto/dashboard;dashboardb\x06proto3"

var (
	file_dashboard_proto_rawDescOnce sync.Once
	file_dashboard_proto_rawDescData []byte
)

func file_dashboard_proto_rawDescGZIP() []byte {
	file_dashboard_proto_rawDescOnce.Do(func() {
		file_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dashboard_proto_rawDesc), len(file_dashboard_proto_rawDesc)))
	})
	return file_dashboard_proto_rawDescData
}

var file_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_dashboard_proto_goTypes = []any{
	(*OverviewCardInfoResponse)(nil),      // 0: dashboard.OverviewCardInfoResponse
	(*UserStatisticsResponse)(nil),        // 1: dashboard.UserStatisticsResponse
	(*UserRoleStatisticsResponse)(nil),    // 2: dashboard.UserRoleStatisticsResponse
	(*MerchantStatisticsResponse)(nil),    // 3: dashboard.MerchantStatisticsResponse
	(*TopMerchantsResponse)(nil),          // 4: dashboard.TopMerchantsResponse
	(*APIStatisticsResponse)(nil),         // 5: dashboard.APIStatisticsResponse
	(*APIResTimeStatisticsResponse)(nil),  // 6: dashboard.APIResTimeStatisticsResponse
	(*TransactionStatisticsResponse)(nil), // 7: dashboard.TransactionStatisticsResponse
	(*TransactionChannelsResponse)(nil),   // 8: dashboard.TransactionChannelsResponse
	(*User)(nil),                          // 9: dashboard.User
	(*Transaction)(nil),                   // 10: dashboard.Transaction
	(*API)(nil),                           // 11: dashboard.API
	(*Activity)(nil),                      // 12: dashboard.Activity
	(*GetTransactionsRequest)(nil),        // 13: dashboard.GetTransactionsRequest
	(*GetTransactionsResponse)(nil),       // 14: dashboard.GetTransactionsResponse
	(*GetUsersRequest)(nil),               // 15: dashboard.GetUsersRequest
	(*GetUsersResponse)(nil),              // 16: dashboard.GetUsersResponse
	(*GetAPIrequests)(nil),                // 17: dashboard.GetAPIrequests
	(*GetAPIReqsResponse)(nil),            // 18: dashboard.GetAPIReqsResponse
	(*GetActivityrequests)(nil),           // 19: dashboard.GetActivityrequests
	(*GetActivityResponse)(nil),           // 20: dashboard.GetActivityResponse
	(*EditUserRequest)(nil),               // 21: dashboard.EditUserRequest
	(*LoginRequest)(nil),                  // 22: dashboard.LoginRequest
	(*DashboardResponse)(nil),             // 23: dashboard.dashboardResponse
}
var file_dashboard_proto_depIdxs = []int32{
	10, // 0: dashboard.GetTransactionsResponse.transactions:type_name -> dashboard.Transaction
	9,  // 1: dashboard.GetUsersResponse.user:type_name -> dashboard.User
	11, // 2: dashboard.GetAPIReqsResponse.request:type_name -> dashboard.API
	12, // 3: dashboard.GetActivityResponse.activity:type_name -> dashboard.Activity
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_dashboard_proto_init() }
func file_dashboard_proto_init() {
	if File_dashboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dashboard_proto_rawDesc), len(file_dashboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dashboard_proto_goTypes,
		DependencyIndexes: file_dashboard_proto_depIdxs,
		MessageInfos:      file_dashboard_proto_msgTypes,
	}.Build()
	File_dashboard_proto = out.File
	file_dashboard_proto_goTypes = nil
	file_dashboard_proto_depIdxs = nil
}
