// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.28.2
// source: hosted_checkout.proto

package hcheckout

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HCheckoutRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CheckoutBaseUrl string                 `protobuf:"bytes,1,opt,name=checkout_base_url,json=checkoutBaseUrl,proto3" json:"checkout_base_url,omitempty"`
	OrderId         string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount          string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"` // Uncomment if needed
	Customer        *Customer              `protobuf:"bytes,4,opt,name=customer,proto3" json:"customer,omitempty"`
	RedirectUrls    *RedirectUrls          `protobuf:"bytes,5,opt,name=redirect_urls,json=redirectUrls,proto3" json:"redirect_urls,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HCheckoutRequest) Reset() {
	*x = HCheckoutRequest{}
	mi := &file_hosted_checkout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HCheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HCheckoutRequest) ProtoMessage() {}

func (x *HCheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hosted_checkout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HCheckoutRequest.ProtoReflect.Descriptor instead.
func (*HCheckoutRequest) Descriptor() ([]byte, []int) {
	return file_hosted_checkout_proto_rawDescGZIP(), []int{0}
}

func (x *HCheckoutRequest) GetCheckoutBaseUrl() string {
	if x != nil {
		return x.CheckoutBaseUrl
	}
	return ""
}

func (x *HCheckoutRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *HCheckoutRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *HCheckoutRequest) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *HCheckoutRequest) GetRedirectUrls() *RedirectUrls {
	if x != nil {
		return x.RedirectUrls
	}
	return nil
}

// Nested message for customer info
type Customer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Customer) Reset() {
	*x = Customer{}
	mi := &file_hosted_checkout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_hosted_checkout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_hosted_checkout_proto_rawDescGZIP(), []int{1}
}

func (x *Customer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Customer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// Nested message for redirect URLs
type RedirectUrls struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       string                 `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`
	Failure       string                 `protobuf:"bytes,2,opt,name=failure,proto3" json:"failure,omitempty"`
	Cancel        string                 `protobuf:"bytes,3,opt,name=cancel,proto3" json:"cancel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectUrls) Reset() {
	*x = RedirectUrls{}
	mi := &file_hosted_checkout_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectUrls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectUrls) ProtoMessage() {}

func (x *RedirectUrls) ProtoReflect() protoreflect.Message {
	mi := &file_hosted_checkout_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectUrls.ProtoReflect.Descriptor instead.
func (*RedirectUrls) Descriptor() ([]byte, []int) {
	return file_hosted_checkout_proto_rawDescGZIP(), []int{2}
}

func (x *RedirectUrls) GetSuccess() string {
	if x != nil {
		return x.Success
	}
	return ""
}

func (x *RedirectUrls) GetFailure() string {
	if x != nil {
		return x.Failure
	}
	return ""
}

func (x *RedirectUrls) GetCancel() string {
	if x != nil {
		return x.Cancel
	}
	return ""
}

type HCheckout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckoutUrl   string                 `protobuf:"bytes,1,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"` // Uncomment if needed
	Customer      *Customer              `protobuf:"bytes,4,opt,name=customer,proto3" json:"customer,omitempty"`
	RedirectUrls  *RedirectUrls          `protobuf:"bytes,5,opt,name=redirect_urls,json=redirectUrls,proto3" json:"redirect_urls,omitempty"`
	CheckoutID    string                 `protobuf:"bytes,6,opt,name=checkoutID,proto3" json:"checkoutID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HCheckout) Reset() {
	*x = HCheckout{}
	mi := &file_hosted_checkout_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HCheckout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HCheckout) ProtoMessage() {}

func (x *HCheckout) ProtoReflect() protoreflect.Message {
	mi := &file_hosted_checkout_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HCheckout.ProtoReflect.Descriptor instead.
func (*HCheckout) Descriptor() ([]byte, []int) {
	return file_hosted_checkout_proto_rawDescGZIP(), []int{3}
}

func (x *HCheckout) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

func (x *HCheckout) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *HCheckout) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *HCheckout) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *HCheckout) GetRedirectUrls() *RedirectUrls {
	if x != nil {
		return x.RedirectUrls
	}
	return nil
}

func (x *HCheckout) GetCheckoutID() string {
	if x != nil {
		return x.CheckoutID
	}
	return ""
}

var File_hosted_checkout_proto protoreflect.FileDescriptor

var file_hosted_checkout_proto_rawDesc = string([]byte{
	0x0a, 0x15, 0x68, 0x6f, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f,
	0x75, 0x74, 0x22, 0xe0, 0x01, 0x0a, 0x10, 0x48, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x6f, 0x75, 0x74, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x42, 0x61, 0x73, 0x65,
	0x55, 0x72, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2f, 0x0a, 0x08, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x68, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x6f, 0x75, 0x74, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x08, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x3c, 0x0a, 0x0d, 0x72, 0x65, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x2e, 0x52, 0x65, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x55, 0x72, 0x6c, 0x73, 0x52, 0x0c, 0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x55, 0x72, 0x6c, 0x73, 0x22, 0x34, 0x0a, 0x08, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x5a, 0x0a, 0x0c, 0x52,
	0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x55, 0x72, 0x6c, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x22, 0xf0, 0x01, 0x0a, 0x09, 0x48, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x6f, 0x75, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75,
	0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x6f, 0x75, 0x74, 0x55, 0x72, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2f, 0x0a, 0x08, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x65, 0x72, 0x52, 0x08, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x3c, 0x0a, 0x0d,
	0x72, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x2e,
	0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x55, 0x72, 0x6c, 0x73, 0x52, 0x0c, 0x72, 0x65,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x55, 0x72, 0x6c, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x49, 0x44, 0x42, 0x1c, 0x5a, 0x1a, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x3b, 0x68,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_hosted_checkout_proto_rawDescOnce sync.Once
	file_hosted_checkout_proto_rawDescData []byte
)

func file_hosted_checkout_proto_rawDescGZIP() []byte {
	file_hosted_checkout_proto_rawDescOnce.Do(func() {
		file_hosted_checkout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hosted_checkout_proto_rawDesc), len(file_hosted_checkout_proto_rawDesc)))
	})
	return file_hosted_checkout_proto_rawDescData
}

var file_hosted_checkout_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_hosted_checkout_proto_goTypes = []any{
	(*HCheckoutRequest)(nil), // 0: hcheckout.HCheckoutRequest
	(*Customer)(nil),         // 1: hcheckout.Customer
	(*RedirectUrls)(nil),     // 2: hcheckout.RedirectUrls
	(*HCheckout)(nil),        // 3: hcheckout.HCheckout
}
var file_hosted_checkout_proto_depIdxs = []int32{
	1, // 0: hcheckout.HCheckoutRequest.customer:type_name -> hcheckout.Customer
	2, // 1: hcheckout.HCheckoutRequest.redirect_urls:type_name -> hcheckout.RedirectUrls
	1, // 2: hcheckout.HCheckout.customer:type_name -> hcheckout.Customer
	2, // 3: hcheckout.HCheckout.redirect_urls:type_name -> hcheckout.RedirectUrls
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_hosted_checkout_proto_init() }
func file_hosted_checkout_proto_init() {
	if File_hosted_checkout_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hosted_checkout_proto_rawDesc), len(file_hosted_checkout_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hosted_checkout_proto_goTypes,
		DependencyIndexes: file_hosted_checkout_proto_depIdxs,
		MessageInfos:      file_hosted_checkout_proto_msgTypes,
	}.Build()
	File_hosted_checkout_proto = out.File
	file_hosted_checkout_proto_goTypes = nil
	file_hosted_checkout_proto_depIdxs = nil
}
