// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: hosted_checkout.proto

package hcheckout

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HCheckoutRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CheckoutBaseUrl string                 `protobuf:"bytes,1,opt,name=checkout_base_url,json=checkoutBaseUrl,proto3" json:"checkout_base_url,omitempty"`
	OrderId         string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount          float32                `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"` // Uncomment if needed
	Customer        *Customer              `protobuf:"bytes,4,opt,name=customer,proto3" json:"customer,omitempty"`
	ReturnUrl       string                 `protobuf:"bytes,5,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	ReceiptRedirect bool                   `protobuf:"varint,6,opt,name=receipt_redirect,json=receiptRedirect,proto3" json:"receipt_redirect,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HCheckoutRequest) Reset() {
	*x = HCheckoutRequest{}
	mi := &file_hosted_checkout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HCheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HCheckoutRequest) ProtoMessage() {}

func (x *HCheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hosted_checkout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HCheckoutRequest.ProtoReflect.Descriptor instead.
func (*HCheckoutRequest) Descriptor() ([]byte, []int) {
	return file_hosted_checkout_proto_rawDescGZIP(), []int{0}
}

func (x *HCheckoutRequest) GetCheckoutBaseUrl() string {
	if x != nil {
		return x.CheckoutBaseUrl
	}
	return ""
}

func (x *HCheckoutRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *HCheckoutRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *HCheckoutRequest) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *HCheckoutRequest) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *HCheckoutRequest) GetReceiptRedirect() bool {
	if x != nil {
		return x.ReceiptRedirect
	}
	return false
}

// Nested message for customer info
type Customer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Customer) Reset() {
	*x = Customer{}
	mi := &file_hosted_checkout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_hosted_checkout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_hosted_checkout_proto_rawDescGZIP(), []int{1}
}

func (x *Customer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Customer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type HCheckout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckoutUrl   string                 `protobuf:"bytes,1,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"` // Uncomment if needed
	Customer      *Customer              `protobuf:"bytes,4,opt,name=customer,proto3" json:"customer,omitempty"`
	ReturnUrl     string                 `protobuf:"bytes,5,opt,name=return_url,json=returnUrl,proto3" json:"return_url,omitempty"`
	CheckoutID    string                 `protobuf:"bytes,6,opt,name=checkoutID,proto3" json:"checkoutID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HCheckout) Reset() {
	*x = HCheckout{}
	mi := &file_hosted_checkout_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HCheckout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HCheckout) ProtoMessage() {}

func (x *HCheckout) ProtoReflect() protoreflect.Message {
	mi := &file_hosted_checkout_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HCheckout.ProtoReflect.Descriptor instead.
func (*HCheckout) Descriptor() ([]byte, []int) {
	return file_hosted_checkout_proto_rawDescGZIP(), []int{2}
}

func (x *HCheckout) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

func (x *HCheckout) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *HCheckout) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *HCheckout) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *HCheckout) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *HCheckout) GetCheckoutID() string {
	if x != nil {
		return x.CheckoutID
	}
	return ""
}

var File_hosted_checkout_proto protoreflect.FileDescriptor

const file_hosted_checkout_proto_rawDesc = "" +
	"\n" +
	"\x15hosted_checkout.proto\x12\thcheckout\"\xec\x01\n" +
	"\x10HCheckoutRequest\x12*\n" +
	"\x11checkout_base_url\x18\x01 \x01(\tR\x0fcheckoutBaseUrl\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x02R\x06amount\x12/\n" +
	"\bcustomer\x18\x04 \x01(\v2\x13.hcheckout.CustomerR\bcustomer\x12\x1d\n" +
	"\n" +
	"return_url\x18\x05 \x01(\tR\treturnUrl\x12)\n" +
	"\x10receipt_redirect\x18\x06 \x01(\bR\x0freceiptRedirect\"4\n" +
	"\bCustomer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"\xd1\x01\n" +
	"\tHCheckout\x12!\n" +
	"\fcheckout_url\x18\x01 \x01(\tR\vcheckoutUrl\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12/\n" +
	"\bcustomer\x18\x04 \x01(\v2\x13.hcheckout.CustomerR\bcustomer\x12\x1d\n" +
	"\n" +
	"return_url\x18\x05 \x01(\tR\treturnUrl\x12\x1e\n" +
	"\n" +
	"checkoutID\x18\x06 \x01(\tR\n" +
	"checkoutIDB\x1cZ\x1a/proto/hcheckout;hcheckoutb\x06proto3"

var (
	file_hosted_checkout_proto_rawDescOnce sync.Once
	file_hosted_checkout_proto_rawDescData []byte
)

func file_hosted_checkout_proto_rawDescGZIP() []byte {
	file_hosted_checkout_proto_rawDescOnce.Do(func() {
		file_hosted_checkout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hosted_checkout_proto_rawDesc), len(file_hosted_checkout_proto_rawDesc)))
	})
	return file_hosted_checkout_proto_rawDescData
}

var file_hosted_checkout_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_hosted_checkout_proto_goTypes = []any{
	(*HCheckoutRequest)(nil), // 0: hcheckout.HCheckoutRequest
	(*Customer)(nil),         // 1: hcheckout.Customer
	(*HCheckout)(nil),        // 2: hcheckout.HCheckout
}
var file_hosted_checkout_proto_depIdxs = []int32{
	1, // 0: hcheckout.HCheckoutRequest.customer:type_name -> hcheckout.Customer
	1, // 1: hcheckout.HCheckout.customer:type_name -> hcheckout.Customer
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_hosted_checkout_proto_init() }
func file_hosted_checkout_proto_init() {
	if File_hosted_checkout_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hosted_checkout_proto_rawDesc), len(file_hosted_checkout_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hosted_checkout_proto_goTypes,
		DependencyIndexes: file_hosted_checkout_proto_depIdxs,
		MessageInfos:      file_hosted_checkout_proto_msgTypes,
	}.Build()
	File_hosted_checkout_proto = out.File
	file_hosted_checkout_proto_goTypes = nil
	file_hosted_checkout_proto_depIdxs = nil
}
