// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: disbursement.proto

package disbursement

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DisbursementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Narration     string                 `protobuf:"bytes,3,opt,name=narration,proto3" json:"narration,omitempty"` // bool isFailed =4;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisbursementRequest) Reset() {
	*x = DisbursementRequest{}
	mi := &file_disbursement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisbursementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisbursementRequest) ProtoMessage() {}

func (x *DisbursementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_disbursement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisbursementRequest.ProtoReflect.Descriptor instead.
func (*DisbursementRequest) Descriptor() ([]byte, []int) {
	return file_disbursement_proto_rawDescGZIP(), []int{0}
}

func (x *DisbursementRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *DisbursementRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DisbursementRequest) GetNarration() string {
	if x != nil {
		return x.Narration
	}
	return ""
}

type DisbursementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	Permissions   []string               `protobuf:"bytes,7,rep,name=permissions,proto3" json:"permissions,omitempty"` // List of permissions granted to the user
	TokenExpiry   string                 `protobuf:"bytes,9,opt,name=tokenExpiry,proto3" json:"tokenExpiry,omitempty"`
	EmailVerified bool                   `protobuf:"varint,10,opt,name=emailVerified,proto3" json:"emailVerified,omitempty"`
	AccountStatus string                 `protobuf:"bytes,11,opt,name=accountStatus,proto3" json:"accountStatus,omitempty"`
	KycStatus     string                 `protobuf:"bytes,12,opt,name=kycStatus,proto3" json:"kycStatus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisbursementResponse) Reset() {
	*x = DisbursementResponse{}
	mi := &file_disbursement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisbursementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisbursementResponse) ProtoMessage() {}

func (x *DisbursementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_disbursement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisbursementResponse.ProtoReflect.Descriptor instead.
func (*DisbursementResponse) Descriptor() ([]byte, []int) {
	return file_disbursement_proto_rawDescGZIP(), []int{1}
}

func (x *DisbursementResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DisbursementResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DisbursementResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DisbursementResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DisbursementResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *DisbursementResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DisbursementResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *DisbursementResponse) GetTokenExpiry() string {
	if x != nil {
		return x.TokenExpiry
	}
	return ""
}

func (x *DisbursementResponse) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *DisbursementResponse) GetAccountStatus() string {
	if x != nil {
		return x.AccountStatus
	}
	return ""
}

func (x *DisbursementResponse) GetKycStatus() string {
	if x != nil {
		return x.KycStatus
	}
	return ""
}

var File_disbursement_proto protoreflect.FileDescriptor

const file_disbursement_proto_rawDesc = "" +
	"\n" +
	"\x12disbursement.proto\x12\fdisbursement\"n\n" +
	"\x13DisbursementRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\x12\x1c\n" +
	"\tnarration\x18\x03 \x01(\tR\tnarration\"\xca\x02\n" +
	"\x14disbursementResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\tR\x02id\x12 \n" +
	"\vpermissions\x18\a \x03(\tR\vpermissions\x12 \n" +
	"\vtokenExpiry\x18\t \x01(\tR\vtokenExpiry\x12$\n" +
	"\remailVerified\x18\n" +
	" \x01(\bR\remailVerified\x12$\n" +
	"\raccountStatus\x18\v \x01(\tR\raccountStatus\x12\x1c\n" +
	"\tkycStatus\x18\f \x01(\tR\tkycStatusB\"Z /proto/disbursement;disbursementb\x06proto3"

var (
	file_disbursement_proto_rawDescOnce sync.Once
	file_disbursement_proto_rawDescData []byte
)

func file_disbursement_proto_rawDescGZIP() []byte {
	file_disbursement_proto_rawDescOnce.Do(func() {
		file_disbursement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_disbursement_proto_rawDesc), len(file_disbursement_proto_rawDesc)))
	})
	return file_disbursement_proto_rawDescData
}

var file_disbursement_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_disbursement_proto_goTypes = []any{
	(*DisbursementRequest)(nil),  // 0: disbursement.DisbursementRequest
	(*DisbursementResponse)(nil), // 1: disbursement.disbursementResponse
}
var file_disbursement_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_disbursement_proto_init() }
func file_disbursement_proto_init() {
	if File_disbursement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_disbursement_proto_rawDesc), len(file_disbursement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_disbursement_proto_goTypes,
		DependencyIndexes: file_disbursement_proto_depIdxs,
		MessageInfos:      file_disbursement_proto_msgTypes,
	}.Build()
	File_disbursement_proto = out.File
	file_disbursement_proto_goTypes = nil
	file_disbursement_proto_depIdxs = nil
}
