// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: card.proto

package card

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CardRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CardNumber     string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardHolderName string                 `protobuf:"bytes,2,opt,name=card_holder_name,json=cardHolderName,proto3" json:"card_holder_name,omitempty"`
	SecurityCode   string                 `protobuf:"bytes,3,opt,name=security_code,json=securityCode,proto3" json:"security_code,omitempty"`
	CardType       string                 `protobuf:"bytes,4,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	Amount         string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency       string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Description    string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	UserId         string                 `protobuf:"bytes,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BaseUrl        string                 `protobuf:"bytes,10,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CardRequest) Reset() {
	*x = CardRequest{}
	mi := &file_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardRequest) ProtoMessage() {}

func (x *CardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardRequest.ProtoReflect.Descriptor instead.
func (*CardRequest) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{0}
}

func (x *CardRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *CardRequest) GetCardHolderName() string {
	if x != nil {
		return x.CardHolderName
	}
	return ""
}

func (x *CardRequest) GetSecurityCode() string {
	if x != nil {
		return x.SecurityCode
	}
	return ""
}

func (x *CardRequest) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *CardRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CardRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CardRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CardRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CardRequest) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

type CardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Id            string                 `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	Permissions   []string               `protobuf:"bytes,7,rep,name=permissions,proto3" json:"permissions,omitempty"` // List of permissions granted to the user
	TokenExpiry   string                 `protobuf:"bytes,8,opt,name=tokenExpiry,proto3" json:"tokenExpiry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardResponse) Reset() {
	*x = CardResponse{}
	mi := &file_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardResponse) ProtoMessage() {}

func (x *CardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardResponse.ProtoReflect.Descriptor instead.
func (*CardResponse) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{1}
}

func (x *CardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CardResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CardResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CardResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CardResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CardResponse) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *CardResponse) GetTokenExpiry() string {
	if x != nil {
		return x.TokenExpiry
	}
	return ""
}

type RequestCode struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TransactionReference string                 `protobuf:"bytes,2,opt,name=transaction_reference,json=transactionReference,proto3" json:"transaction_reference,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RequestCode) Reset() {
	*x = RequestCode{}
	mi := &file_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCode) ProtoMessage() {}

func (x *RequestCode) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCode.ProtoReflect.Descriptor instead.
func (*RequestCode) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{2}
}

func (x *RequestCode) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RequestCode) GetTransactionReference() string {
	if x != nil {
		return x.TransactionReference
	}
	return ""
}

type VerifyCode struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Code                 string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	UserId               string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TransactionReference string                 `protobuf:"bytes,3,opt,name=transaction_reference,json=transactionReference,proto3" json:"transaction_reference,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *VerifyCode) Reset() {
	*x = VerifyCode{}
	mi := &file_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCode) ProtoMessage() {}

func (x *VerifyCode) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCode.ProtoReflect.Descriptor instead.
func (*VerifyCode) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *VerifyCode) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyCode) GetTransactionReference() string {
	if x != nil {
		return x.TransactionReference
	}
	return ""
}

var File_card_proto protoreflect.FileDescriptor

const file_card_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"card.proto\x12\x04card\"\xa4\x02\n" +
	"\vcardRequest\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\x12(\n" +
	"\x10card_holder_name\x18\x02 \x01(\tR\x0ecardHolderName\x12#\n" +
	"\rsecurity_code\x18\x03 \x01(\tR\fsecurityCode\x12\x1b\n" +
	"\tcard_type\x18\x04 \x01(\tR\bcardType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x17\n" +
	"\auser_id\x18\t \x01(\tR\x06userId\x12\x19\n" +
	"\bbase_url\x18\n" +
	" \x01(\tR\abaseUrl\"\xd8\x01\n" +
	"\fcardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\tR\x02id\x12 \n" +
	"\vpermissions\x18\a \x03(\tR\vpermissions\x12 \n" +
	"\vtokenExpiry\x18\b \x01(\tR\vtokenExpiry\"[\n" +
	"\vRequestCode\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x123\n" +
	"\x15transaction_reference\x18\x02 \x01(\tR\x14transactionReference\"n\n" +
	"\n" +
	"VerifyCode\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x123\n" +
	"\x15transaction_reference\x18\x03 \x01(\tR\x14transactionReferenceB\x12Z\x10/proto/card;cardb\x06proto3"

var (
	file_card_proto_rawDescOnce sync.Once
	file_card_proto_rawDescData []byte
)

func file_card_proto_rawDescGZIP() []byte {
	file_card_proto_rawDescOnce.Do(func() {
		file_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_card_proto_rawDesc), len(file_card_proto_rawDesc)))
	})
	return file_card_proto_rawDescData
}

var file_card_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_card_proto_goTypes = []any{
	(*CardRequest)(nil),  // 0: card.cardRequest
	(*CardResponse)(nil), // 1: card.cardResponse
	(*RequestCode)(nil),  // 2: card.RequestCode
	(*VerifyCode)(nil),   // 3: card.VerifyCode
}
var file_card_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_card_proto_init() }
func file_card_proto_init() {
	if File_card_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_card_proto_rawDesc), len(file_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_card_proto_goTypes,
		DependencyIndexes: file_card_proto_depIdxs,
		MessageInfos:      file_card_proto_msgTypes,
	}.Build()
	File_card_proto = out.File
	file_card_proto_goTypes = nil
	file_card_proto_depIdxs = nil
}
